name = "clipix-ai-new"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[vars]
NEXT_PUBLIC_RENDER_API_URL = "https://render-clipex-ai.kilincarslanenterprises.com"
